name: Update Traffic Data

on:
  schedule:
    - cron: '0 * * * *'  # Spustí se každou hodinu (přizpůsobit podle potřeby)

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Fetch traffic data and save to JSON files
        run: node fetch-traffic-data.js

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git add evidence_traffic_data.json invoice_client_traffic_data.json invoice_server_traffic_data.json
          git commit -m "Update traffic data"
          git push

