name: Fetch GitHub Data

on:
  schedule:
    - cron: '0 * * * *'  # Spustí se každou hodinu (nastav si podle potřeby)

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Fetch data from EvidencePojistenych
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/JiriMusilCZ/EvidencePojistenych/traffic/views > evidence_traffic_data.json

    - name: Fetch data from invoice-client-starter
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/JiriMusilCZ/invoice-client-starter/traffic/views > invoice_client_traffic_data.json

    - name: Fetch data from invoice-server-starter
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/JiriMusilCZ/invoice-server-starter/traffic/views > invoice_server_traffic_data.json

    - name: Commit and push data
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add evidence_traffic_data.json invoice_client_traffic_data.json invoice_server_traffic_data.json
        git commit -m "Update traffic data"
        git push
