name: Fetch Data

on:
  schedule:
    - cron: '0 * * * *'  # Spustí se každou hodinu
  workflow_dispatch:

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    env:
      GH_PAT: ${{ secrets.GH_PAT }}  # Nastavení proměnné prostředí

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch data for EvidencePojistenych
        run: |
          curl -H "Authorization: token $GH_PAT" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/JiriMusilCZ/EvidencePojistenych/traffic/views \
               -o evidence_traffic_data.json

      - name: Fetch data for invoice-client-starter
        run: |
          curl -H "Authorization: token $GH_PAT" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/JiriMusilCZ/invoice-client-starter/traffic/views \
               -o invoice_client_traffic_data.json

      - name: Fetch data for invoice-server-starter
        run: |
          curl -H "Authorization: token $GH_PAT" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/JiriMusilCZ/invoice-server-starter/traffic/views \
               -o invoice_server_traffic_data.json
