name: Update Traffic Data

on:
  schedule:
    - cron: '0 * * * *' # Spouští se každou hodinu
  workflow_dispatch: # Umožňuje ruční spuštění workflow

jobs:
  update-data:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Umožňuje workflow zapisovat do repozitáře

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch data
        run: |
          # Načti data z GitHub API do JSON souborů
          curl -H "Accept: application/vnd.github.v3+json" \
               -H "Authorization: token ${{ secrets.GH_PAT }}" \
               -o evidence_traffic_data.json \
               "https://api.github.com/repos/JiriMusilCZ/EvidencePojistenych/traffic/views"

          curl -H "Accept: application/vnd.github.v3+json" \
               -H "Authorization: token ${{ secrets.GH_PAT }}" \
               -o invoice_client_traffic_data.json \
               "https://api.github.com/repos/JiriMusilCZ/invoice-client-starter/traffic/views"

          curl -H "Accept: application/vnd.github.v3+json" \
               -H "Authorization: token ${{ secrets.GH_PAT }}" \
               -o invoice_server_traffic_data.json \
               "https://api.github.com/repos/JiriMusilCZ/invoice-server-starter/traffic/views"

      - name: Commit and push updated data
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add evidence_traffic_data.json invoice_client_traffic_data.json invoice_server_traffic_data.json
          git commit -m "Update traffic data" || echo "No changes to commit"
          git pull --rebase origin main # Stáhne změny z remote repozitáře a integruje je do tvé větve
          git push

